- Logic/Core/MoveGeneration.cs
- Logic/Search/Searches.cs
As pointed out by [cj5716](https://github.com/cj5716), move generation during quiescence searches could be improved by only generating the moves that fit the current move ordering criteria, as opposed to generating every move and filtering them after. This is a fairly significant speedup (somewhere around 10-15%), and only changes bench by a small amount.
```
Elo   | 7.82 +- 4.90 (95%)
Games | N: 9958 W: 2686 L: 2462 D: 4810
Penta | [104, 1134, 2306, 1304, 131]
http://somelizard.pythonanywhere.com/test/263/
```
> Faster quiescence movegen

- Logic/NN/Bucketed768.cs
- Logic/NN/NNUE.cs
- Logic/NN/Simple768.cs
- Program.cs
The "load" command will replace the loaded weights with the new ones, so long as the network architectures are the same.
> Added a command to load weights from another network file

- Logic/Transposition/TTEntry.cs
No functional change. This only avoids masking and shifting by changing how the data is stored.
```
Elo   | 0.12 +- 2.77 (95%)
LLR   | -0.85 (-2.94, 2.94) [-1.00, 3.00]
Games | N: 32394 W: 8710 L: 8699 D: 14985
Penta | [439, 3656, 7981, 3697, 424]
http://somelizard.pythonanywhere.com/test/492/
```
> Split score and static eval fields in TT entries

- Logic/Magic/MagicBitboards.cs
- Logic/Util/Utilities.cs
- Makefile
No significant change in performance for most CPU's, but should help AMD processors earlier than Zen 3.
```
Elo   | 2.00 +- 5.16 (95%)
LLR   | 0.47 (-2.94, 2.94) [0.00, 3.00]
Games | N: 8862 W: 2288 L: 2237 D: 4337
Penta | [82, 995, 2209, 1080, 65]
http://somelizard.pythonanywhere.com/test/488/
```
> Choose to enable pext at startup

- Logic/Core/Position.cs
- Logic/Search/SearchStackEntry.cs
- Logic/Search/Searches.cs
- Logic/Util/Utilities.cs
This reordered lines to standardize how Negamax and QSearch look, and also removed the unnecessary "StatScore" variable.
> Search Cleanups

- Logic/Search/History/CaptureHistoryTable.cs
- Logic/Search/History/ContinuationHistory.cs
- Logic/Search/History/MainHistoryTable.cs
- Logic/Search/History/PieceToHistory.cs
- Logic/Search/History/StatEntry.cs
- Logic/Search/MovePicker.cs
- Logic/Search/Ordering/HistoryTable.cs
- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/SearchStackEntry.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Main/Capture histories are now in their own files and are now indexed implicitly with `HistoryIndex`/`CapIndex`, which is easier to work with.
- History is now stored in `StatEntry`, which is just a wrapper over a `short`. 
- Bonuses are applied using the `<<=` operator, instead of `history.ApplyBonus`.
> History Cleanups 

- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
MultiPV (incorrectly) allowed moves sorted before the current root move to be searched, which caused issues with the root move scores and messy output.
> Fix MultiPV Output

- .github/workflows/makefile.yml
- .gitignore
- Lizard.csproj
- Logic/NN/Bucketed768.cs
- Logic/NN/Bucketed768Unroll.cs
- Logic/NN/FunUnrollThings.cs
- Logic/NN/NNUE.cs
- Logic/NN/Simple768.cs
- Logic/NN/Simple768Unroll.cs
- Logic/Util/IsAOTHandler.cs
- Logic/Util/Utilities.cs
- Makefile
- Program.cs
- Properties/PublishProfiles/Release-win64-aot.pubxml
- Properties/PublishProfiles/Release-win64-dev.pubxml
- Properties/PublishProfiles/Release-win64-pext.pubxml
- Properties/PublishProfiles/Release-win64.pubxml
- README.md
- Avx-512 will only be used if "AVX512" is one of the DefineConstants. 
- PUBLISH_AOT is no longer required to be defined for AOT to not break.
- Standardizes much of the code between the bucketed and unbucketed arches so there is less repetition.
> Added AVX-512 SIMD

- Logic/Search/Searches.cs
```
Elo   | 14.67 +- 7.10 (95%)
Games | N: 4762 W: 1333 L: 1132 D: 2297
Penta | [29, 495, 1155, 650, 52]
http://somelizard.pythonanywhere.com/test/652/
```
```
Elo   | 11.47 +- 8.85 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=32MB
LLR   | 1.55 (-2.94, 2.94) [0.00, 3.00]
Games | N: 2940 W: 779 L: 682 D: 1479
Penta | [5, 304, 758, 395, 8]
http://somelizard.pythonanywhere.com/test/650/
```
> Save evaluation in non-hit TT entries

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
This is speculative...
```
Elo   | 7.05 +- 5.93 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=32MB
LLR   | 1.95 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6358 W: 1598 L: 1469 D: 3291
Penta | [19, 679, 1658, 800, 23]
http://somelizard.pythonanywhere.com/test/645/
```
> More negative extensions in SE

- Logic/Search/Searches.cs
```
Elo   | 4.25 +- 3.49 (95%)
Games | N: 19530 W: 5146 L: 4907 D: 9477
Penta | [172, 2241, 4725, 2430, 197]
http://somelizard.pythonanywhere.com/test/660/
```
Essentially untested at LTC:
```
Elo   | -0.60 +- 19.60 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=32MB
LLR   | -0.04 (-2.94, 2.94) [0.00, 3.00]
Games | N: 576 W: 137 L: 138 D: 301
Penta | [0, 69, 152, 66, 1]
http://somelizard.pythonanywhere.com/test/665/
```
> Apply LMR to non-PV captures

- Logic/NN/Bucketed768.cs
- Logic/NN/Bucketed768Unroll.cs
- Properties/Resources.Designer.cs
- Properties/Resources.resx
```
Elo   | 7.78 +- 3.95 (95%)
Games | N: 9956 W: 2779 L: 2556 D: 4621
Penta | [97, 1127, 2352, 1260, 142]
http://somelizard.pythonanywhere.com/test/703/
```
> 5 input buckets, 8 material scaling outputs

- Logic/Transposition/TTEntry.cs
- Logic/Transposition/TranspositionTable.cs
```
Elo   | 3.33 +- 2.32 (95%)
Games | N: 26286 W: 6935 L: 6683 D: 12668
Penta | [216, 3006, 6470, 3212, 239]
http://somelizard.pythonanywhere.com/test/649/
```
> Reworked TTEntry depth/structure

- Logic/Search/Searches.cs
```
Elo   | 5.30 +- 3.09 (95%)
Games | N: 14412 W: 3701 L: 3481 D: 7230
Penta | [112, 1584, 3592, 1808, 110]
http://somelizard.pythonanywhere.com/test/746/
```
> Weight previous conthist more in LMR

- Logic/Search/Searches.cs
QSearch used to save the current depth into TT entries, but because the depth decreases for each recursive QSearch call this caused entries with sufficiently large negative depths to wrap around to 255 and be treated as having a very high depth instead of a low one. 
Thanks to @yl25946 for mentioning a similar issue and giving me the idea to look into this further.
```
Elo   | 3.83 +- 2.53 (95%)
Games | N: 21210 W: 5419 L: 5185 D: 10606
Penta | [132, 2422, 5293, 2596, 162]
http://somelizard.pythonanywhere.com/test/758/
```
Even more apparent under higher hash pressure:
```
Elo   | 5.84 +- 3.25 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=1MB
Games | N: 12664 W: 3215 L: 3002 D: …
```
> Save a minimum depth of -1 in QSearch

- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/SearchOptions.cs
- Logic/UCI/UCIClient.cs
This was a surprisingly large error... oops
```
Elo   | 10.18 +- 4.42 (95%)
Games | N: 6758 W: 1785 L: 1587 D: 3386
Penta | [27, 740, 1665, 902, 45]
http://somelizard.pythonanywhere.com/test/815/
```
> Removed capture history heuristic divisor

- Logic/Core/Position.cs
- Logic/Core/StateInfo.cs
- Logic/Data/Move.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/Transposition/Cuckoo.cs
- Logic/Transposition/Zobrist.cs
This added a `PliesFromNull` field to position states, and may have also fixed a subtle issue with GamePly and IsThreefoldRepetition. 
Negamax/QSearch are now directly passed the position as a parameter instead of having it be passed indirectly via a `SearchInformation` object.
```
Elo   | 12.27 +- 4.92 (95%)
Games | N: 5664 W: 1452 L: 1252 D: 2960
Penta | [32, 602, 1375, 780, 43]
http://somelizard.pythonanywhere.com/test/890/
```
> Added Cuckoo repetition detection

- Logic/Threads/SearchThread.cs
```
Elo   | 2.34 +- 1.79 (95%)
Games | N: 41586 W: 10215 L: 9935 D: 21436
Penta | [239, 4855, 10355, 5075, 269]
http://somelizard.pythonanywhere.com/test/892/
```
> Use average score in aspiration windows

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/UCI/UCIClient.cs
```
Elo   | 6.19 +- 3.36 (95%)
Games | N: 11964 W: 3054 L: 2841 D: 6069
Penta | [72, 1347, 2939, 1544, 80]
http://somelizard.pythonanywhere.com/test/816/
```
Doesn't seem to scale well:
```
Elo   | 2.68 +- 2.70 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=32MB
LLR   | 1.51 (-2.94, 2.94) [0.00, 3.00]
Games | N: 15294 W: 3650 L: 3532 D: 8112
Penta | [24, 1685, 4114, 1797, 27]
http://somelizard.pythonanywhere.com/test/822/
```
> Reduce more in NMP based on eval

- Logic/Search/Searches.cs
```
Elo   | 5.90 +- 3.26 (95%)
Games | N: 12420 W: 3137 L: 2926 D: 6357
Penta | [71, 1362, 3150, 1539, 88]
http://somelizard.pythonanywhere.com/test/900/
```
> Adjust return value of QSearch beta cuts

- Logic/Search/Searches.cs
```
Elo   | 5.07 +- 2.98 (95%)
Games | N: 14814 W: 3740 L: 3524 D: 7550
Penta | [77, 1676, 3694, 1874, 86]
http://somelizard.pythonanywhere.com/test/905/
```
depth - 2 appeared to gain, but not as much as depth - 3: http://somelizard.pythonanywhere.com/test/909/
depth - 5 which looked negative: http://somelizard.pythonanywhere.com/test/906/
> Raise Probcut verification depth by 1

- Logic/Transposition/TranspositionTable.cs
- Logic/Util/Interop.cs
Only used for Linux systems, and might give a slight speedup.
Vs main:
```
Elo   | 2.96 +- 2.11 (95%)
Games | N: 28550 W: 7501 L: 7258 D: 13791
Penta | [241, 2837, 7858, 3116, 223]
http://somelizard.pythonanywhere.com/test/873/
```
And this is apparently not solely due to the alignment being a larger power of 2 (2^20 instead of 2^6).
Align 2^20, madvise vs. no madvise:
```
Elo   | 5.97 +- 3.27 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 3.00]
Games | N: 12172 W: 3240 L: 3031 D: 5901
Penta | [102, 1192, 3298, 1383, 111]
http://somelizard.pythonanywhere.com/test/971/
```
> Enabled huge pages for the transposition table

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/UCI/UCIClient.cs
```
Elo   | 5.61 +- 3.18 (95%)
Games | N: 13244 W: 3358 L: 3144 D: 6742
Penta | [75, 1492, 3285, 1684, 86]
http://somelizard.pythonanywhere.com/test/962/
```
Neutral-ish at LTC:
```
Elo   | 0.87 +- 7.57 (95%)
Conf  | 40.0+0.40s Threads=1 Hash=32MB
Games | N: 2002 W: 475 L: 470 D: 1057
Penta | [2, 236, 521, 239, 3]
http://somelizard.pythonanywhere.com/test/963/
```
> 10k iteration STC tune 

- Logic/Threads/SearchThread.cs
```
Elo   | 11.60 +- 4.74 (95%)
Games | N: 5902 W: 1571 L: 1374 D: 2957
Penta | [23, 624, 1492, 757, 55]
http://somelizard.pythonanywhere.com/test/981/
```
```
Elo   | 5.92 +- 3.55 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=32MB
LLR   | 2.36 (-2.94, 2.94) [0.00, 3.00]
Games | N: 9162 W: 2249 L: 2093 D: 4820
Penta | [17, 985, 2433, 1117, 29]
http://somelizard.pythonanywhere.com/test/991/
```
> Adjust depth for aspiration window fails

- Logic/NN/Bucketed768.cs
- Properties/Resources.Designer.cs
- Properties/Resources.resx
Added 0.8b DFRC positions, and retrained from superbatch 315 using cosine annealing.
Might be slightly better at standard:
```
Elo   | 2.23 +- 2.90 (95%)
LLR   | 2.23 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 15904 W: 4000 L: 3898 D: 8006
Penta | [107, 1814, 4006, 1920, 105]
http://somelizard.pythonanywhere.com/test/1058/
```
And significantly better at DFRC:
```
Elo   | 26.55 +- 7.99 (95%)
Games | N: 3108 W: 911 L: 674 D: 1523
Penta | [67, 264, 678, 455, 90]
http://somelizard.pythonanywhere.com/test/1059/
```
> Retrained network with DFRC data

- Logic/Core/Position.cs
- Logic/NN/Accumulator.cs
- Logic/NN/Bucketed768.cs
- Logic/NN/Bucketed768Unroll.cs
- Logic/NN/NNUE.cs
- Logic/NN/NetworkUpdate.cs
A very significant speedup:
```
Elo   | 29.84 +- 7.81 (95%)
Games | N: 2346 W: 718 L: 517 D: 1111
Penta | [16, 190, 578, 355, 34]
http://somelizard.pythonanywhere.com/test/1133/
```
```
Elo   | 27.52 +- 7.03 (95%)
Games | N: 2252 W: 644 L: 466 D: 1142
Penta | [7, 152, 641, 308, 18]
http://somelizard.pythonanywhere.com/test/1136/
```
The implementation is based on Ciekce/Stormphrax#165
> Added lazy NNUE updates

- GlobalUsings.cs
- Lizard.csproj
- Logic/Core/Bitboard.cs
- Logic/Core/MoveGeneration.cs
- Logic/Core/Position.cs
- Logic/Data/Move.cs
- Logic/NN/Bucketed768.cs
- Logic/NN/NNUE.cs
- Logic/NN/NetworkUpdate.cs
- Logic/Search/Evaluation.cs
- Logic/Search/History/MainHistoryTable.cs
- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/Transposition/Cuckoo.cs
- Logic/Transposition/TranspositionTable.cs
- Logic/Util/ExceptionHandling.cs
- Logic/Util/Interop.cs
- Makefile
Reverts to non-AOT compilation by default, which is now faster apparently:
```
Elo   | 16.24 +- 5.63 (95%)
Games | N: 4132 W: 1130 L: 937 D: 2065
Penta | [32, 359, 1096, 542, 37]
http://somelizard.pythonanywhere.com/test/1142/
```
Also added a few AggressiveInlining attributes in logical places. The changes to the Move classes properties (`move.From`, `move.To`, etc.) might be reverted in the future if it becomes annoying. Most of the speedup here comes from the non-AOT part, not the inlining.
> Default to non-AOT compilation

- Logic/Core/Bitboard.cs
- Logic/Core/Position.cs
- Logic/Core/PrecomputedData.cs
- Logic/Data/PredicateType.cs
- Logic/Magic/MagicBitboards.cs
- Logic/NN/Accumulator.cs
- Logic/NN/Bucketed768.cs
- Logic/Search/History/CaptureHistoryTable.cs
- Logic/Search/History/ContinuationHistory.cs
- Logic/Search/History/MainHistoryTable.cs
- Logic/Search/History/PieceToHistory.cs
- Logic/Search/Ordering/HistoryTable.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/Transposition/Cuckoo.cs
- Logic/Transposition/TranspositionTable.cs
- Logic/Util/Interop.cs
- Logic/Util/Utilities.cs
Did non-reg with HasNonPawnMaterial bugged, which was still fine.
```
Elo   | -0.36 +- 2.60 (95%)
LLR   | 1.31 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 17588 W: 4482 L: 4500 D: 8606
Penta | [121, 1778, 5012, 1764, 119]
http://somelizard.pythonanywhere.com/test/1184/
```
> General cleanups

- Logic/Core/MoveGeneration.cs
- Logic/Core/Position.cs
This deals with castling movegen in a DRY manner. This also replaces the `InCheck`/`InDoubleCheck` fields with getters that consider the current state's `Checkers` mask, and removes `idxChecker` since it is only used in one place.
```
Elo   | 1.56 +- 3.02 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 12668 W: 3250 L: 3193 D: 6225
Penta | [72, 1257, 3624, 1304, 77]
http://somelizard.pythonanywhere.com/test/1208/
```
> Simplified Position fields

- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/SearchStackEntry.cs
- Logic/Search/Searches.cs
```
Elo   | 3.01 +- 3.82 (95%)
LLR   | 2.99 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 8772 W: 2192 L: 2116 D: 4464
Penta | [39, 1004, 2239, 1050, 54]
http://somelizard.pythonanywhere.com/test/1218/
```
> Removed second killer move

- Logic/Core/MoveGeneration.cs
- Logic/Core/Position.cs
- Logic/Data/Move.cs
- Logic/NN/Bucketed768.cs
- Logic/Search/History/MainHistoryTable.cs
- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/Transposition/Cuckoo.cs
- Logic/Util/Utilities.cs
Simplifications to movegen, including generating promotions in QNRB order and reverting the previous Move property changes.
```
Elo   | 1.34 +- 2.98 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 13986 W: 3477 L: 3423 D: 7086
Penta | [68, 1589, 3616, 1661, 59]
http://somelizard.pythonanywhere.com/test/1257/
```
> Movegen changes

- Logic/Search/SearchStackEntry.cs
- Logic/Search/Searches.cs
Move structs haven't been 4 bytes in a few months, and by reordering the fields the total size can be reduced to 32.
```
Elo   | 2.04 +- 3.27 (95%)
LLR   | 2.97 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 10892 W: 2793 L: 2729 D: 5370
Penta | [75, 1032, 3168, 1096, 75]
http://somelizard.pythonanywhere.com/test/1258/
```
> Reordered SearchStackEntry layout

- Logic/Search/Searches.cs
This reduces the number of cutnodes accepted by probcut's current criteria.
```
Elo   | 4.66 +- 2.81 (95%)
Games | N: 16044 W: 3981 L: 3766 D: 8297
Penta | [71, 1793, 4085, 1996, 77]
http://somelizard.pythonanywhere.com/test/1387/
```
> Do IIR before probcut

- Logic/Core/Bitboard.cs
- Logic/Core/Position.cs
- Logic/Data/Move.cs
- Logic/Data/RootMove.cs
- Logic/Magic/MagicBitboards.cs
- Logic/NN/Accumulator.cs
- Logic/NN/Bucketed768.cs
- Logic/Search/Searches.cs
- Logic/Transposition/TTEntry.cs
- Logic/Util/Utilities.cs
This has a relatively minimal effect on search elo, but increases perft speed by nearly 50%.
```
Elo   | 7.29 +- 3.65 (95%)
Games | N: 9678 W: 2569 L: 2366 D: 4743
Penta | [69, 962, 2586, 1141, 81]
http://somelizard.pythonanywhere.com/test/1393/
```
> Re-added inlinings and added SkipLocalsInit

- Logic/Search/Searches.cs
Probably doesn't scale but I'm tired of looking at this
```
Elo   | 1.24 +- 0.96 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 135460 W: 33390 L: 32905 D: 69165
Penta | [586, 15648, 34887, 15913, 696]
http://somelizard.pythonanywhere.com/test/1273/
```
```
Elo   | 0.52 +- 1.80 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=64MB
LLR   | -0.38 (-2.94, 2.94) [0.00, 3.00]
Games | N: 34740 W: 8276 L: 8224 D: 18240
Penta | [64, 3939, 9318, 3979, 70]
http://somelizard.pythonanywhere.com/test/1283/
```
> Don't save exact entries in QSearch

- Logic/Threads/SearchThread.cs
```
Elo   | 4.22 +- 2.60 (95%)
Games | N: 17052 W: 4189 L: 3982 D: 8881
Penta | [50, 1794, 4652, 1959, 71]
```
http://somelizard.pythonanywhere.com/test/1430/
> Added score stability TM component

- Logic/Search/Searches.cs
```
Elo   | 2.67 +- 1.96 (95%)
Games | N: 32404 W: 7855 L: 7606 D: 16943
Penta | [123, 3691, 8361, 3868, 159]
```
http://somelizard.pythonanywhere.com/test/1474/
> Base Probcut SEE on beta and eval

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/UCI/UCIClient.cs
```
Elo   | 2.74 +- 1.99 (95%)
Games | N: 31658 W: 7952 L: 7702 D: 16004
Penta | [151, 3573, 8120, 3845, 140]
```
http://somelizard.pythonanywhere.com/test/1537/
> Reduce cutnodes more, extend ttpv

- Logic/Search/Ordering/MoveOrdering.cs
- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/UCI/UCIClient.cs
The capture divisor was arbitrarily chosen to be 2000 less than the normal divisor, so it's currently about 5/6th of the value.
The names of most UCI options were also shortened and their unhelpful comments were removed because they were getting a bit out of hand.
```
Elo   | 2.51 +- 1.88 (95%)
Games | N: 37018 W: 9512 L: 9245 D: 18261
Penta | [192, 4313, 9254, 4536, 214]
```
http://somelizard.pythonanywhere.com/test/1548/
> Use CaptureHistory in LMR

- Logic/Search/Searches.cs
This is only done when running single-threaded since doing this with multiple threads is expensive and pointless.
> Obey node limiting exactly

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/UCI/UCIClient.cs
The current margin is 4x the double margin, and is increased by a further ~3x for captures
```
Elo   | 2.82 +- 1.99 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
Games | N: 27466 W: 6769 L: 6546 D: 14151
Penta | [29, 2981, 7490, 3204, 29]
```
http://somelizard.pythonanywhere.com/test/1558/
> Allow triple extensions

- Logic/Search/History/CorrectionTables.cs
- Logic/Search/History/ICorrectionTable.cs
- Logic/Search/Searches.cs
```
Elo   | 2.57 +- 1.92 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 36478 W: 8952 L: 8682 D: 18844
Penta | [195, 4296, 9040, 4460, 248]
```
http://somelizard.pythonanywhere.com/test/1615/
> Factor both sides for non-pawn correction

- Logic/Search/Searches.cs
Also removes the `+ 1` from the bonus' depth.
```
Elo   | 4.90 +- 2.93 (95%)
Games | N: 15602 W: 3876 L: 3656 D: 8070
Penta | [83, 1815, 3788, 2029, 86]
```
http://somelizard.pythonanywhere.com/test/1658/
> Penalize capture moves with the correct malus

- Logic/Search/Searches.cs
```
Elo   | 7.01 +- 3.61 (95%)
Games | N: 10410 W: 2638 L: 2428 D: 5344
Penta | [51, 1201, 2502, 1389, 62]
```
http://somelizard.pythonanywhere.com/test/1666/
> Don't factor low depth cutoffs in history

- Logic/Search/Searches.cs
Idea first tried in Stockfish by Vizvezdenec here: https://github.com/official-stockfish/Stockfish/commit/7c30091a92abddb8265e53768b32751c49642040
```
Elo   | 4.17 +- 2.63 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 18980 W: 4652 L: 4424 D: 9904
Penta | [71, 2248, 4675, 2374, 122]
```
http://somelizard.pythonanywhere.com/test/1683/
> Added Probcut-like evasion pruning

- Logic/Search/Searches.cs
```
Elo   | 3.94 +- 2.54 (95%)
Games | N: 19748 W: 4866 L: 4642 D: 10240
Penta | [85, 2266, 4950, 2486, 87]
```
http://somelizard.pythonanywhere.com/test/1695/
> Adjusted Probcut evasion depth

- Logic/Search/Searches.cs
This hasn't been a problem before but occurred fairly frequently when testing more complicated NNUE architectures. 
```
Elo   | 0.35 +- 2.33 (95%)
LLR   | 3.03 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 23066 W: 5560 L: 5537 D: 11969
Penta | [97, 2729, 5847, 2774, 86]
```
http://somelizard.pythonanywhere.com/test/1783/
> Prevent explosions during LMR research

- Logic/Core/MoveGeneration.cs
- Logic/Search/Searches.cs
- Logic/Util/Utilities.cs
The inclusion of non-capture moves that give check during initial QSearch calls likely hurt probcut and LMR reductions by a significant amount.
A surprise, to be sure, but a welcome one.
```
Elo   | 21.43 +- 6.36 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 3068 W: 840 L: 651 D: 1577
Penta | [11, 271, 789, 444, 19]
```
http://somelizard.pythonanywhere.com/test/1820/
> Removed QSearch depth logic

- Logic/Search/Searches.cs
```
Elo   | -0.24 +- 1.97 (95%)
LLR   | 2.74 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 32308 W: 7584 L: 7606 D: 17118
Penta | [114, 3901, 8151, 3869, 119]
```
http://somelizard.pythonanywhere.com/test/1822/
> Standardize values in SEE

- Logic/NN/Bucketed768.cs
- network.txt
Significantly helps DFRC
```
Elo   | 82.28 +- 15.07 (95%)
Games | N: 1114 W: 429 L: 170 D: 515
Penta | [6, 84, 207, 165, 95]
```
http://somelizard.pythonanywhere.com/test/1866/
Also had a decent gain in fixed-nodes in standard:
```
Elo   | 14.66 +- 4.73 (95%)
Conf  | N=25000 Threads=1 Hash=16MB
Games | N: 10006 W: 3334 L: 2912 D: 3760
Penta | [261, 1070, 2014, 1302, 356]
```
http://somelizard.pythonanywhere.com/test/1860/
> 8 input buckets with a factorizer

- Logic/Search/Searches.cs
- Logic/Util/Utilities.cs
```
Elo   | 1.74 +- 1.39 (95%)
Games | N: 63868 W: 15234 L: 14915 D: 33719
Penta | [197, 7531, 16164, 7840, 202]
```
http://somelizard.pythonanywhere.com/test/1942/
> Added 50mr scaling

- Logic/UCI/UCIClient.cs
- Logic/Util/Utilities.cs
- Program.cs
This should free the ~50mb used by the byte[] when decompressing a zstd file, among other smaller things. The garbage collector runs so infrequently that this memory would sometimes never be collected at all, which is a waste.
> Force GC before entering UCI

- Logic/Search/SearchOptions.cs
- Logic/Search/Searches.cs
- Logic/Util/Utilities.cs
```
Elo   | 2.56 +- 1.89 (95%)
Games | N: 34908 W: 8326 L: 8069 D: 18513
Penta | [117, 4099, 8771, 4344, 123]
```
http://somelizard.pythonanywhere.com/test/2006/
> Different IIR conditions

- Logic/Search/Searches.cs
- Logic/Threads/SearchThread.cs
- Logic/Threads/SearchThreadPool.cs
- Logic/Util/Utilities.cs
This mainly helps with zugzwang in endgames
```
Elo   | 2.02 +- 1.56 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 47528 W: 11308 L: 11032 D: 25188
Penta | [102, 5376, 12563, 5590, 133]
```
http://somelizard.pythonanywhere.com/test/2024/
> Added NMP verification search

- Logic/Search/Searches.cs
- Logic/Util/Utilities.cs
```
Elo   | 1.59 +- 1.28 (95%)
Games | N: 75050 W: 17933 L: 17589 D: 39528
Penta | [240, 8846, 19001, 9206, 232]
```
http://somelizard.pythonanywhere.com/test/1967/
> Save probcut results to TT

- .gitignore
- Bindings/SIMD.cpp
- Bindings/arch.h
- Bindings/defs.h
- Bindings/simd.h
- Lizard.csproj
- Logic/NN/Bucketed768.cs
- Logic/Util/HorsieBindings.cs
- Logic/Util/Utilities.cs
- Makefile
Makefile will attempt to compile the c++ code into a dll/so, and include it in the binary. This are an improvement on the existing Avx2 implementation, and the fallbacks will still work if your system doesn't have `g++`.
```
Elo   | 24.86 +- 6.77 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
Games | N: 2436 W: 657 L: 483 D: 1296
Penta | [4, 198, 640, 372, 4]
```
https://somelizard.pythonanywhere.com/test/2208/
> Added optional C++ P/Invoke for evaluation
